# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yv-W-gYB9ENCA0v7eQI4MTKQPOuU5Bf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("/content/Student_Performance.csv")

df.head()

df.columns

df.drop('Extracurricular Activities', axis=1, inplace=True)

df

x = df[['Hours Studied', 'Previous Scores',
       'Sleep Hours', 'Sample Question Papers Practiced',]]
y = df['Performance Index']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("✅ Predictions:", y_pred)

plt.scatter(y_test, y_pred)
plt.xlabel("Previous Score")
plt.ylabel("Hours Studied")
plt.title("Actual vs. Predicted Performance Index")
plt.show()